#!/usr/bin/env python3
"""Derive the web design tokens from the Swift source.

The Swift app is the source of truth. This reads `Theme.swift` and the seeded categories
in `LogCategory.swift`, and writes:

    design/tokens.json          the extracted values, for anything else that wants them
    web/src/styles/tokens.css   CSS custom properties for the web harness

Run with --check to verify the generated files are current; it exits non-zero if they are
not. That is the whole point: two hand-maintained definitions of the same colours drift
silently, and this project has already paid for that lesson once.

    python3 scripts/extract_tokens.py
    python3 scripts/extract_tokens.py --check
"""
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
THEME = ROOT / "WUUT" / "Shared" / "Theme.swift"
CATEGORIES = ROOT / "WUUT" / "Model" / "LogCategory.swift"
JSON_OUT = ROOT / "design" / "tokens.json"
CSS_OUT = ROOT / "web" / "src" / "styles" / "tokens.css"

# Identifiers may contain digits (ink2, ink3) — an earlier pattern without \d silently
# dropped both, which is exactly the class of bug this script exists to prevent.
COLOR_RE = re.compile(r'static let ([A-Za-z][A-Za-z0-9]*)\s*=\s*Color\(hex:\s*"([0-9A-Fa-f]{6})"\)')
FLOAT_RE = re.compile(r'static let ([A-Za-z][A-Za-z0-9]*)\s*:\s*CGFloat\s*=\s*([0-9.]+)')
CATEGORY_RE = re.compile(
    r'\(\s*"([^"]+)"\s*,\s*"([0-9A-Fa-f]{6})"\s*,\s*"([0-9A-Fa-f]{6})"\s*,\s*"([^"]+)"\s*\)'
)


def kebab(name: str) -> str:
    """rule Faint -> rule-faint, ink2 -> ink-2."""
    s = re.sub(r'(?<=[a-z])(?=[A-Z])', '-', name)
    s = re.sub(r'(?<=[A-Za-z])(?=\d)', '-', s)
    return s.lower()


def slug(name: str) -> str:
    return re.sub(r'[^a-z0-9]+', '-', name.lower()).strip('-')


def extract():
    theme = THEME.read_text()
    colors = {name: value.upper() for name, value in COLOR_RE.findall(theme)}
    floats = {name: float(value) for name, value in FLOAT_RE.findall(theme)}

    cat_src = CATEGORIES.read_text()
    # Only the seeded table, not any tuple elsewhere in the file. The slice must begin
    # after the `= [`, because the declaration's own type annotation contains a `]` and
    # scanning for the first one lands inside it.
    start = cat_src.index("public static let all:")
    start = cat_src.index("= [", start) + len("= [")
    end = cat_src.index("\n    ]", start)
    categories = [
        {"name": n, "hex": light.upper(), "symbol": symbol}
        for n, light, _dark, symbol in CATEGORY_RE.findall(cat_src[start:end])
    ]

    if not colors or not categories:
        raise SystemExit("extract failed: Theme.swift or LogCategory.swift did not parse")

    return {
        "$comment": "Generated by scripts/extract_tokens.py from the Swift source. Do not edit.",
        "source": {"theme": "WUUT/Shared/Theme.swift", "categories": "WUUT/Model/LogCategory.swift"},
        "colors": colors,
        "metrics": floats,
        "categories": categories,
    }


def render_css(tokens) -> str:
    lines = [
        "/* Generated by scripts/extract_tokens.py from WUUT/Shared/Theme.swift.",
        " * Do not edit — run the script. `--check` fails the build if this drifts.",
        " *",
        " * ui-serif and ui-monospace resolve to New York and SF Mono on macOS, which is",
        " * exactly what SwiftUI's .serif and .monospaced designs resolve to on iOS. So on a",
        " * Mac this harness renders the app's real typefaces, which the Figma file cannot.",
        " */",
        ":root {",
    ]
    for name, hex_value in tokens["colors"].items():
        lines.append(f"  --{kebab(name)}: #{hex_value};")
    lines.append("")
    for name, value in tokens["metrics"].items():
        rendered = int(value) if value == int(value) else value
        lines.append(f"  --{kebab(name)}: {rendered}px;")
    lines.append("")
    lines.append("  /* Seeded categories. Colour is reinforcement only — the weakest pair is")
    lines.append("     ΔE 7.7, so every appearance also carries the category's name. */")
    for category in tokens["categories"]:
        lines.append(f"  --category-{slug(category['name'])}: #{category['hex']};")
    lines.append("")
    lines.append("  --font-serif: ui-serif, 'New York', Georgia, serif;")
    lines.append("  --font-mono: ui-monospace, 'SF Mono', 'IBM Plex Mono', monospace;")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main():
    check = "--check" in sys.argv
    tokens = extract()
    json_text = json.dumps(tokens, indent=2, ensure_ascii=False) + "\n"
    css_text = render_css(tokens)

    if check:
        stale = []
        for path, expected in ((JSON_OUT, json_text), (CSS_OUT, css_text)):
            if not path.exists() or path.read_text() != expected:
                stale.append(str(path.relative_to(ROOT)))
        if stale:
            print("Design tokens are out of date: " + ", ".join(stale))
            print("Run: python3 scripts/extract_tokens.py")
            return 1
        print(f"Tokens current — {len(tokens['colors'])} colours, {len(tokens['categories'])} categories.")
        return 0

    JSON_OUT.parent.mkdir(parents=True, exist_ok=True)
    CSS_OUT.parent.mkdir(parents=True, exist_ok=True)
    JSON_OUT.write_text(json_text)
    CSS_OUT.write_text(css_text)
    print(f"Wrote {JSON_OUT.relative_to(ROOT)} and {CSS_OUT.relative_to(ROOT)}")
    print(f"  {len(tokens['colors'])} colours, {len(tokens['metrics'])} metrics, {len(tokens['categories'])} categories")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
